working_dir: "."
app_prompt:
  base_dir: "prompts/staging"
  prompt_patterns:
    - "**/*.md"
    - "**/*.txt"
  ignore_patterns:
    - "**/temp/**"
app_schema:
  base_dir: "schemas/staging"
  schema_patterns:
    - "**/*.json"
    - "**/*.yaml"
  ignore_patterns:
    - "**/draft/**"
cache:
  enable: true
  ttl: 1800
  cleanup_interval: 43200
logging:
  level: "warn"
  output: "console"
  file_path: "/tmp/staging.log"
database:
  host: "staging-db.example.com"
  port: 5432
  pool_size: 10
  timeout: 15000
api:
  rate_limit: 500
  timeout: 10000
  retry_attempts: 2