name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Run tests
        run: |
          # Run tests from src directory first
          deno test --allow-read --allow-write --allow-env src/*_test.ts
          # Then run tests from tests directory
          deno test --allow-read --allow-write --allow-env tests/**/*_test.ts

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check
        run: deno check src/mod.ts 