name: Publish

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Publish to Deno
        run: deno publish 