name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run type checking
        run: deno check **/*.ts

      - name: Run tests
        run: deno test --allow-read --allow-write --allow-env --coverage=cov_profile

      - name: Generate coverage report
        run: deno coverage cov_profile --lcov --output=cov_profile.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./cov_profile.lcov
          fail_ci_if_error: true

  result-type-tests:
    runs-on: ubuntu-latest
    name: Result Type Integration Tests

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run Result type tests
        run: |
          echo "Running Result type specific tests..."
          deno test tests/config/error_test.ts --allow-read --allow-write --allow-env
          deno test tests/test_helpers/result_test_helpers.ts --allow-read --allow-write --allow-env

      - name: Check Result type usage
        run: |
          echo "Checking Result type implementation..."
          # Verify all Safe methods are implemented
          grep -r "Safe(" src/ | grep -E "(load|get|create)" || echo "No Safe methods found"

          # Verify Result type imports
          grep -r "import.*Result.*from" src/ | grep -v "test" || echo "No Result imports found"

  validate-phase-completion:
    runs-on: ubuntu-latest
    name: Validate Phase Completion

    steps:
      - uses: actions/checkout@v3

      - name: Check Phase 1-3 completion
        run: |
          echo "Validating Phase 1-3 implementation..."

          # Check for Result type definitions
          test -f src/types/config_result.ts || exit 1
          test -f src/types/unified_result.ts || exit 1

          # Check for Safe loaders
          test -f src/loaders/safe_config_loader.ts || exit 1

          # Check for validators
          test -f src/validators/config_validator.ts || exit 1
          test -f src/validators/path_validator.ts || exit 1

          echo "Phase 1-3 files verified ✓"

      - name: Check documentation
        run: |
          echo "Checking documentation..."
          test -f docs/totality.md || exit 1
          test -f docs/error-handling-guide.md || exit 1
          test -f docs/phase-status-summary.md || exit 1
          echo "Documentation files verified ✓"
